### ISSUE TITLE
Solr Cloud backup won't clean up data after the backup finishes sucessfully

### ISSUE THREAD

**Issue by krishnachalla-hv** [apache/lucene-solr-operator#130]
**Describe the bug**
When we use solr cloud backup resource to take the backup into long term persistence storage it won't clean up the data which is used to take the backup. According to the backup job arguments there one particular line to do the clean up. But it is not happening right now.

**To Reproduce**
1. Solr cloud should be up and running(I am using solr-7.5.0-slim image)
2. Then create the collection and populate documents into it
3. Run the solr-operator solrCloud backup job to take the backup

There are no errors in the pod also. I did **kuectl logs solr-backup**. I got the below O/P
`/`

**Expected behavior**
It should clean the data in short term pvc.

**Screenshots**

**Environment (please complete the following information):**
 - Operating System and Version: Ubuntu Linux 18.04

**Additional context**
I have created 2 pvcs one for backupResoteVolume under SolrCloud Resource and one for SolrBacku```
backupRestoreVolume:
  persistentVolumeClaim:
    claimName: solr-backup
```
The above one I used for SolrCloud with accessMode **ReadWriteMany**.

```
.
persistentVolumeClaim:
  claimName: solr-restore-volume
```
This one I used for SolrBackup with accessMode **ReadWritOnce**.

**Comment by sepulworld** [comment]
What are the underlying storage systems? In particular what are you using for backupRestoreVolume?

**Comment by krishnachalla-hv** [comment]
I am using `PersistentVolumeClaim` to take the backup.

**Comment by sepulworld** [comment]
What exactly is the technology behind the PV though? Is it AWS EBS? NFS, etc. 

Please show us a 'kubectl describe storageclass' on the type of storageclass you are using for PV/PVC.

**Comment by krishnachalla-hv** [comment]
I am running it on minikube. after doing `kubectl describe pv  pvc-079a01d4-81ee-48e6-b8bb-f2b6dd2707d1`

```
Name:            pvc-079a01d4-81ee-48e6-b8bb-f2b6dd2707d1
Labels:          <none>
Annotations:     hostPathProvisionerIdentity: d5a91215-e36d-11ea-af65-080027292b29
                 pv.kubernetes.io/provisioned-by: k8s.io/minikube-hostpath
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    standard
Status:          Bound
Claim:           default/ldc-czd-solr-backup-restore-volume-claim
Reclaim Policy:  Delete
Access Modes:    RWX
VolumeMode:      Filesystem
Capacity:        10Gi
Node Affinity:   <none>
Message:         
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /tmp/hostpath-provisioner/pvc-079a01d4-81ee-48e6-b8bb-f2b6dd2707d1
    HostPathType:  
Events:            <none>
```

**Comment by HoustonPutman** [comment]
This should be fixed now with: https://github.com/bloomberg/solr-operator/commit/6024117d746dc3f00915f1789d416a845f7fd7cd
