### ISSUE TITLE
kubectl apply -f crds.yaml fails with metadata.annotations: Too long error

### ISSUE THREAD

**Issue by zhuopeng** [apache/lucene-solr-operator#215]
To reproduce
`kubectl apply -f helm/solr-operator/crds/crds.yaml`

getting error
`customresourcedefinition.apiextensions.k8s.io/solrbackups.solr.bloomberg.com configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
customresourcedefinition.apiextensions.k8s.io/solrcollectionaliases.solr.bloomberg.com configured
customresourcedefinition.apiextensions.k8s.io/solrcollections.solr.bloomberg.com configured
customresourcedefinition.apiextensions.k8s.io/solrprometheusexporters.solr.bloomberg.com configured
The CustomResourceDefinition "solrclouds.solr.bloomberg.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`

It happens for any version >0.2.6

It is likely related to this https://github.com/kubernetes/kubectl/issues/712. When using kubectl apply to install CRD, kubectl apply use "last-applied-configuration" to store previous CRD configuration. And it exceed the limit.

**Comment by HoustonPutman** [comment]
Use `kubectl replace` instead, it's what we use in the Makefile now. For CRDs, `replace` is better than `apply`, even without the annotation.
