### ISSUE TITLE
Enhancements for working with basic auth enabled Solr clusters

### ISSUE THREAD

**Issue by thelabdude** [apache/lucene-solr-operator#218]
For background on Solr basic auth, see: 
https://lucene.apache.org/solr/guide/8_8/basic-authentication-plugin.html#basic-authentication-plugin

The Solr operator should provide an easy way to enable basic authentication for a SolrCloud cluster.

There are two main uses cases we should support:

1. The operator should bootstrap a default `security.json` with basic auth enabled. This allows users to easily spin-up a secure Solr cluster without having to know all the details of how Solr security works. Having the Solr API be protected by basic-auth out of the box leads to a better getting started experience for Solr and the operator in general.
2. The operator should allow users to supply their own `security.json` (via ConfigMap) and corresponding secret with credentials the operator should use to make API requests to Solr. Both are needed and if the user chooses to supply their own `security.json` then they need to make sure the credentials are in the secret as well. For this use case, the operator's main job is to bootstrap the `security.json` in ZK as part of the initialization process.

When basic auth is enabled, we need to ensure the liveness / readiness probes work (`/admin/info/system` endpoint). In addition, the rolling restart logic requires access to the `/admin/collections` endpoint. Also, backup / restore requires API access. Thus, the Solr operator needs access to a username and password to make API calls. These credentials will come from a Kubernetes secret in the same namespace.

For the first use case (bootstrap a default config), the only tricky part is we need to create the user password hashes in the same manner that Solr expects them. The default `security.json` will define an `admin` user, a general purpose read-only `solr` user, and special `k8s-oper` user that *only* has read access to the API endpoints needed to operator in Kubernetes, such as the `/admin/info/system` endpoint used by probes. The password for each user can be retrieved using `kubectl` using:
```
kubectl get secret dev-solrcloud-basic-auth -o jsonpath='{.data.k8s-oper}' | base64 --decode
```

Also, I'm not sure if the operator should watch the `security.json` ConfigMap for updates (as we do with other user-provided ConfigMaps) and try to apply the updated JSON? There's an API for updating the security config and the ref guide suggests using that so maybe the operator just bootstraps the file and then it's up to users to maintain via the API? Trying to accommodate user updates via the API and/or ConfigMap could get messy.

For the probes, K8s allows specifying a header for HTTP endpoints, but then our password will live in the STS config. I think it would be better to set an env var from the secret and then run a command for the probe using this env var. The SolrCLI command-line tool provides an `api` action that we can use for the probes:
```
java -Dbasicauth=k8s-oper:****** \
  -Dsolr.httpclient.builder.factory=org.apache.solr.client.solrj.impl.PreemptiveBasicAuthClientBuilderFactory \
  -Dsolr.install.dir="/opt/solr" \
  -Dlog4j.configurationFile="/opt/solr/server/resources/log4j2-console.xml" \
  -classpath "/opt/solr/server/solr-webapp/webapp/WEB-INF/lib/*:/opt/solr/server/lib/ext/*:/opt/solr/server/lib/*" \
  org.apache.solr.util.SolrCLI api -get http://localhost:8983/solr/admin/info/system
```
Unfortunately, `bin/solr` does not expose the `api` action :-( So we'll need to take some liberties on how the probe command is constructed, such as assuming Solr is installed at `/opt/solr`

Still testing / tweaking the default `security.json` but I imagine it would be something like this:
```
{
      "authentication":{
        "blockUnknown": true,
        "class":"solr.BasicAuthPlugin",
        "credentials": {
          "admin":  "...",
          "k8s-oper":     "...",
          "solr":   "..."
        },
        "realm":"Solr Basic Auth",
        "forwardCredentials": false
      },
      "authorization": {
         "class": "solr.RuleBasedAuthorizationPlugin",
         "user-role": {
            "admin": ["admin", "probe"],
            "k8s-oper": ["probe"],
            "solr": ["users", "probe"]
         },
         "permissions": [
           { "name": "k8s-probes", "role":"probe", "collection": null, "path":"/admin/info/system" },
           { "name": "k8s-status", "role":"probe", "collection": null, "path":"/admin/collections" },
           { "name": "all", "role":["admin","users"] },
           { "name": "read", "role":["admin","users"] },
           { "name": "update", "role":["admin"] },
           { "name": "security-read", "role": "admin"},
           { "name": "security-edit", "role": "admin"}
         ]
      }
    }
```

**Comment by anshumg** [comment]
Just having `#1` done for now sounds like a good place to be in. `#2` adds complexity and requires the operator to deal with more than what the users might want currently.
