### ISSUE TITLE
Investigate supporting standalone Solr

### ISSUE THREAD

**Issue by HoustonPutman** [apache/lucene-solr-operator#3]
Currently the operator only supports Solr Cloud, however there are many still using standalone Solr. Investigate the way that standalone Solr could be implemented as a separate CRD in the operator, and if the operator would give any benefit for standalone instances.

**Comment by sepulworld** [comment]
I can look into this. It would be very beneficial for local development environments on laptops I believe. Less pods will require less resources (battery, CPU mainly). People probably using for production deployments as well.

**Comment by janhoy** [comment]
I don't see a clear benefit of having a master/slave variant if you are actually targeting k8s. We should rather make it super easy to spin up a cluster with only 1 pod and 1 zk pod.

This way, all the other operations such as upload configset, create collection etc will remain the same as for a huge SolrCloud cluster. If you agree, please close this as won't do.

**Comment by HoustonPutman** [comment]
Agree with @janhoy.
